import { Router } from "express";
import { createUsers } from "../Controllers/signupController";
import { loginUsers } from "../Controllers/loginController";
import { getAllPosts } from "../Controllers/allPostsController";
import { addPost } from "../Controllers/profileController/addPostController";
import { deletePost } from "../Controllers/profileController/deletePostController";
import { editPost } from "../Controllers/profileController/editPostController";
import { getPreviousPost } from "../Controllers/profileController/previousPostDisplayController";
import { searchForPost } from "../Controllers/searchForPostController";
import { addRating } from "../Controllers/addRatingController";
import { protect } from "../middleware/authenticationMiddleware";
const router = Router();
router.post("/signup", createUsers);
router.post("/login", loginUsers);
router.get("/getAllposts", protect, getAllPosts);
router.post("/addPosts", protect, addPost);
router.delete("/deletePost", protect, deletePost);
router.put("/editPost", protect, editPost);
router.put("/addRating", protect, addRating);
router.get("/previousPosts", protect, getPreviousPost);
router.get("/searchForPost", protect, searchForPost);

export default router;
